### ISSUE TITLE
使用“3”个参数调用“UploadString”时发生异常

### ISSUE THREAD

**Issue by mokeyjay** [lixuy/CloudXNS-DDNS-with-PowerShell#3]
![Snipaste_2019-02-03_21-14-50.png](https://i.loli.net/2019/02/03/5c56e97b75c99.png)

Win10 LTSC
确认网络正常

这个报错是指CloudXNS的服务挂了吗？已经好几天了耶

**Comment by kkkgo** [comment]
收到，我等下看看
话说你是我qq好友23333

**Comment by mokeyjay** [comment]
欸~QQ几乎没怎么用了，都不记得有加了谁
现在不是tg就是微信惹

**Comment by kkkgo** [comment]
![clo.png](https://i.loli.net/2019/02/03/5c56ece9ce2e4.png)
我这里好像正常惹

**Comment by kkkgo** [comment]
https://www.cloudxns.net/AccountManage/userlog.html
看看日志能不能看到些信息

**Comment by mokeyjay** [comment]
![Snipaste_2019-02-03_23-41-07.png](https://i.loli.net/2019/02/03/5c570ba102810.png)
emmmm...似乎通过API更新的解析记录的信息都是英文的，而中文都是我手动更新的

**Comment by mokeyjay** [comment]
摸了：[https://github.com/mokeyjay/CloudXNS-DDNS-client-php](https://github.com/mokeyjay/CloudXNS-DDNS-client-php)  
（溜

**Comment by kkkgo** [comment]
https://github.com/kkkgo/CloudXNS-DDNS-with-BashShell
可以试试这个哦
